version: '3.8'

services:
  gunthy:
    image: riemannulus/gunthy:latest  # Pull image from Docker Hub
    # build:  # Uncomment below for local build
    #   context: .
    #   dockerfile: Dockerfile
    container_name: gunthy
    restart: unless-stopped
    
    # Port mapping
    ports:
      - "3000:3000"   # GUI access (browser: http://localhost:3000)
      - "3001:3001"   # GUI default port
      - "5001:5001"   # WebSocket port
    
    # Data volume mount (all persistent data stored here)
    volumes:
      - ./gunthy_data:/data
      # Optional: Mount specific subdirectories to host for easy access
      # - ./host_logs:/data/logs
      # - ./host_config:/data/config
      # - ./host_backups:/data/backups
    
    # Environment variables
    environment:
      - TZ=Asia/Seoul          # Timezone setting
      - USE_PM2=false          # Set to 'true' to run with PM2 process manager
      # - GUNTHY_HOME=/opt/gunthy  # Already set in Dockerfile
      # - GUNTHY_DATA=/data        # Already set in Dockerfile
    
    # Network mode (optional)
    # network_mode: "host"     # Uncomment if you need host network access
